// examples/vue-app/src/components/FHECounterDemo.vue
<!-- FHECounterDemo.vue -->
<template>
  <div class="fhe-counter-demo">
    <div class="card bg-base-100 shadow-xl">
      <div class="card-body">
        <h2 class="card-title text-3xl justify-center mb-2">🔐 FHE Counter Demo</h2>
        <p class="text-center text-base-content/70 mb-6">Fully Homomorphic Encryption on Ethereum</p>

        <!-- Debug Toggle Button -->
        <div class="flex justify-center mb-6 gap-2 flex-wrap">
          <button
            @click="handleDebugToggle"
            :class="isDebugMode ? 'btn-info' : 'btn-ghost'"
            class="btn btn-sm gap-2"
            title="Toggle debug mode"
          >
            🐛 Debug {{ isDebugMode ? 'ON' : 'OFF' }}
          </button>
        </div>

        <!-- FHEVM Instance Status -->
        <div class="mb-6">
          <h3 class="text-lg font-semibold mb-3">FHEVM Instance</h3>
          <div class="badge badge-lg" :class="fhevmStatusBadgeClass">
            <span class="loading loading-spinner loading-xs mr-1" v-if="fhevmStatus === 'loading'"></span>
            {{ fhevmStatusText }}
          </div>
          <p v-if="fhevmError" class="text-error text-sm mt-2">{{ fhevmErrorMessage }}</p>
          <button
            v-if="fhevmStatus === 'error'"
            @click="refreshFhevm"
            class="btn btn-outline btn-sm mt-2"
          >
            Retry
          </button>
        </div>

        <!-- Counter Display -->
        <Transition name="fade">
          <div v-if="fhevmStatus === 'ready'" class="space-y-6">
            <div class="bg-base-200 rounded-lg p-6">
              <h3 class="text-lg font-semibold mb-4">Counter Value</h3>

              <!-- Encrypted Handle -->
              <div class="mb-4">
                <label class="label">
                  <span class="label-text font-medium">Encrypted Handle:</span>
                </label>
                <div class="flex items-center gap-2">
                  <code class="flex-1 bg-base-300 px-3 py-2 rounded" v-if="handle">{{ shortHandle }}</code>
                  <span v-else class="text-base-content/50 italic">No handle yet</span>
                  <button
                    @click="refreshCountHandle"
                    :disabled="!canGetCount || isRefreshing"
                    class="btn btn-ghost btn-sm"
                    title="Refresh"
                  >
                    <span class="loading loading-spinner loading-xs" v-if="isRefreshing"></span>
                    <span v-else>🔄</span>
                  </button>
                </div>
              </div>

              <!-- Decrypted Value with Animation -->
              <Transition name="slide-fade" mode="out-in">
                <div v-if="isDecrypted" class="text-center" key="decrypted">
                  <label class="label">
                    <span class="label-text font-medium">Decrypted Value:</span>
                  </label>
                  <div class="text-6xl font-bold text-primary my-4">{{ decryptedValue }}</div>
                </div>
                <div v-else class="text-center" key="encrypted">
                  <label class="label">
                    <span class="label-text font-medium">Decrypted Value:</span>
                  </label>
                  <div class="text-4xl font-bold text-base-content/50 my-4">🔒 Encrypted</div>
                  <button
                    @click="decryptCountHandle"
                    :disabled="!canDecrypt || isDecrypting"
                    class="btn btn-primary"
                  >
                    <span class="loading loading-spinner loading-sm" v-if="isDecrypting"></span>
                    <span v-else>Decrypt</span>
                  </button>
                </div>
              </Transition>
            </div>

            <!-- Counter Controls -->
            <div class="bg-base-200 rounded-lg p-6">
              <h4 class="text-lg font-semibold mb-4">Update Counter</h4>

              <!-- Input Group -->
              <div class="form-control mb-4">
                <label class="label">
                  <span class="label-text font-medium">Increment/Decrement Value:</span>
                </label>
                <input
                  v-model.number="inputValue"
                  type="number"
                  min="-100"
                  max="100"
                  class="input input-bordered"
                  :disabled="!canUpdateCounter || isProcessing"
                  @keyup.enter="handleUpdate"
                />
              </div>

              <!-- Quick Action Buttons -->
              <div class="grid grid-cols-2 gap-2 mb-4">
                <button
                  @click="handleIncrement(1)"
                  :disabled="!canUpdateCounter || isProcessing"
                  class="btn btn-success"
                >
                  +1
                </button>
                <button
                  @click="handleIncrement(5)"
                  :disabled="!canUpdateCounter || isProcessing"
                  class="btn btn-success"
                >
                  +5
                </button>
                <button
                  @click="handleDecrement(1)"
                  :disabled="!canUpdateCounter || isProcessing"
                  class="btn btn-error"
                >
                  -1
                </button>
                <button
                  @click="handleDecrement(5)"
                  :disabled="!canUpdateCounter || isProcessing"
                  class="btn btn-error"
                >
                  -5
                </button>
              </div>

              <!-- Custom Update Button -->
              <button
                @click="handleUpdate"
                :disabled="!canUpdateCounter || isProcessing || inputValue === 0"
                class="btn btn-primary w-full"
              >
                <span class="loading loading-spinner loading-sm" v-if="isProcessing"></span>
                <span v-else-if="inputValue > 0">Increment by {{ inputValue }}</span>
                <span v-else-if="inputValue < 0">Decrement by {{ Math.abs(inputValue) }}</span>
                <span v-else>Enter a value</span>
              </button>
            </div>

            <!-- Status Message with Transition -->
            <Transition name="slide-up">
              <div v-if="message" class="alert" :class="messageAlertClass">
                <span>{{ message }}</span>
              </div>
            </Transition>
          </div>
        </Transition>

        <!-- Not Connected State -->
        <div v-if="!isConnected" class="text-center py-8 text-base-content/60">
          <p>👆 Please connect your wallet to interact with the FHE Counter</p>
        </div>

        <!-- Wrong Network State -->
        <div v-if="isConnected && chainId !== 31337 && chainId !== 11155111" class="alert alert-warning">
          <span>⚠️ Please switch to Hardhat Local (31337) or Sepolia (11155111)</span>
        </div>
      </div>

      <!-- Global Error Alert -->
      <Transition name="slide-down">
        <div v-if="showErrorAlert" class="alert alert-error shadow-lg">
          <div class="flex-1">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4v2m0 0a9 9 0 110-18 9 9 0 010 18z"></path>
            </svg>
            <span>{{ globalErrorMessage }}</span>
          </div>
          <button @click="clearError" class="btn btn-sm btn-ghost">Close</button>
        </div>
      </Transition>

      <!-- Contract Info -->
      <div class="card-actions justify-end p-6 bg-base-200">
        <div class="collapse collapse-arrow border border-base-300 flex-1">
          <input type="checkbox" />
          <div class="collapse-title text-sm font-medium">Contract Details</div>
          <div class="collapse-content">
            <p class="text-sm"><strong>Contract Address:</strong></p>
            <code class="text-xs block bg-base-300 p-2 rounded mt-1">{{ contractAddress || 'Not deployed' }}</code>
            <p class="text-sm mt-2"><strong>Network:</strong> {{ networkName }}</p>
          </div>
        </div>
      </div>

    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { useFhevm } from '@fhevm-sdk/vue'
import { useWallet } from '@/composables/useWallet'
import { useFHECounter } from '@/composables/useFHECounter'
import { useIndexedDBStorage } from '@/composables/useIndexedDBStorage'
import { useDebugMode } from '@/lib/utils/debugHelper'
import { useErrorHandler } from '@/lib/utils/errorHandler'
import config from '@/config' // Still needed for mockChains and targetNetworks in other parts

// Initialize utilities
const { initializeDebugMode, toggleDebugMode, isDebugEnabled } = useDebugMode()
const { errorMessage: globalErrorMessage, isVisible: showErrorAlert, clearError } = useErrorHandler()

// Debug mode state (local state to track UI, separate from SDK state)
const debugEnabled = ref(false)

// Initialize debug mode on component mount
onMounted(() => {
  initializeDebugMode()
  debugEnabled.value = isDebugEnabled()

  // Log component initialization
  console.log('🔐 FHECounterDemo component mounted')
  console.log('📝 Debug logs available in browser Developer Tools Console')
})

// Handle debug toggle
const handleDebugToggle = () => {
  const newState = toggleDebugMode()
  debugEnabled.value = newState
  console.log(`Debug mode ${newState ? 'enabled' : 'disabled'}`)
}

// Wallet connection
const { chainId, isConnected, provider, signer } = useWallet()

// Raw provider ref for FHEVM (avoid ethers wrapper to prevent "Cannot access private method")
const rawProvider = computed(() => {
  if (typeof window !== 'undefined' && window.ethereum) {
    return window.ethereum as any
  }
  return undefined
})

// FHEVM instance - pass window.ethereum directly, not ethers wrapper
const {
  instance: fhevmInstance,
  status: fhevmStatus,
  error: fhevmError,
  errorMessage: fhevmErrorMessage,
  refresh: refreshFhevm,
} = useFhevm({
  provider: rawProvider, // Use raw provider
  chainId: chainId,
  enabled: computed(() => isConnected.value && rawProvider.value !== undefined),
  initialMockChains: config.mockChains,
  retry: {
    maxRetries: 3,
    retryDelay: 2000,
  },
  onSuccess: () => {
    console.log('FHEVM instance created successfully!')
  },
})

// Storage for decryption signatures (IndexedDB - persistent across page reloads)
const { storage: storageRef, error: storageError } = useIndexedDBStorage({
  dbName: 'fhevm-vue-app',
  storeName: 'signatures',
})

// Show storage initialization error if any
watch(storageError, (newError) => {
  if (newError) {
    console.warn('[FHECounterDemo] Storage initialization warning:', newError)
  }
})

// FHE Counter operations
const {
  contractAddress,
  handle,
  decryptedValue,
  isDecrypted,
  canGetCount,
  canDecrypt,
  canUpdateCounter,
  isRefreshing,
  isDecrypting,
  isProcessing,
  message,
  refreshCountHandle,
  decryptCountHandle,
  updateCounter,
} = useFHECounter({
  instance: fhevmInstance,
  chainId,
  signer,
  provider,
  storage: storageRef,  // Pass reactive ref for persistence across page reloads
  mockChains: config.mockChains,
})

// Input value (v-model binding)
const inputValue = ref(1)

// Debug mode controls
const isDebugMode = computed(() => debugEnabled.value)

// Update computed properties untuk DaisyUI classes
const fhevmStatusText = computed(() => {
  switch (fhevmStatus.value) {
    case 'idle': return 'Idle'
    case 'loading': return 'Loading...'
    case 'ready': return 'Ready ✓'
    case 'error': return 'Error'
    default: return fhevmStatus.value
  }
})

const fhevmStatusBadgeClass = computed(() => {
  switch (fhevmStatus.value) {
    case 'idle': return 'badge-outline'
    case 'loading': return 'badge-info badge-outline'
    case 'ready': return 'badge-success'
    case 'error': return 'badge-error'
    default: return 'badge-outline'
  }
})

const messageAlertClass = computed(() => {
  const msg = message.value.toLowerCase()
  if (msg.includes('error') || msg.includes('failed')) return 'alert-error'
  if (msg.includes('success') || msg.includes('completed')) return 'alert-success'
  return 'alert-info'
})

const shortHandle = computed(() => {
  if (!handle.value) return ''
  return `${handle.value.slice(0, 10)}...${handle.value.slice(-8)}`
})

const networkName = computed(() => {
  if (!chainId.value) return 'Unknown'
  const network = config.targetNetworks.find(n => n.id === chainId.value)
  return network?.name || `Chain ${chainId.value}`
})

// Action handlers
const handleIncrement = (value: number) => {
  inputValue.value = value
  updateCounter(value)
}

const handleDecrement = (value: number) => {
  inputValue.value = -value
  updateCounter(-value)
}

const handleUpdate = () => {
  if (inputValue.value !== 0) {
    updateCounter(inputValue.value)
  }
}

// Vue-specific: Watch handle changes and auto-clear decrypted value
watch(handle, (newHandle, oldHandle) => {
  if (newHandle !== oldHandle && newHandle) {
    console.log('Handle changed:', newHandle)
  }
})
</script>

<style scoped>
/* Custom transitions and animations */
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.slide-fade-enter-active {
  transition: all 0.3s ease-out;
}

.slide-fade-leave-active {
  transition: all 0.2s cubic-bezier(1, 0.5, 0.8, 1);
}

.slide-fade-enter-from {
  transform: translateY(20px);
  opacity: 0;
}

.slide-fade-leave-to {
  transform: translateY(-20px);
  opacity: 0;
}

.slide-up-enter-active,
.slide-up-leave-active {
  transition: all 0.3s ease;
}

.slide-up-enter-from {
  transform: translateY(10px);
  opacity: 0;
}

.slide-up-leave-to {
  transform: translateY(-10px);
  opacity: 0;
}

.slide-down-enter-active,
.slide-down-leave-active {
  transition: all 0.3s ease;
}

.slide-down-enter-from {
  transform: translateY(-10px);
  opacity: 0;
}

.slide-down-leave-to {
  transform: translateY(-10px);
  opacity: 0;
}
</style>

// packages/nextjs/app/_components/FHECounterDemo.tsx
"use client";

import { useMemo, useState, useEffect } from "react";
import { useFhevm } from "@fhevm-sdk";
import { useAccount } from "wagmi";
import { RainbowKitCustomConnectButton } from "~~/components/helper/RainbowKitCustomConnectButton";
import { useFHECounterWagmi } from "~~/hooks/fhecounter-example/useFHECounterWagmi";
import { useIndexedDBStorage } from "~~/hooks/helper/useIndexedDBStorage";
import { toggleDebugMode, isDebugEnabled, initializeDebugMode, logDebug } from "~/lib/utils";

/*
 * Main FHECounter React component with 3 buttons
 *  - "Decrypt" button: allows you to decrypt the current FHECounter count handle.
 *  - "Increment" button: allows you to increment the FHECounter count handle using FHE operations.
 *  - "Decrement" button: allows you to decrement the FHECounter count handle using FHE operations.
 *
 * Uses IndexedDB storage for persistent decryption signatures (survives page reload).
 */
export const FHECounterDemo = () => {
  const { isConnected, chain } = useAccount();
  const [debugEnabled, setDebugEnabled] = useState(false);

  const chainId = chain?.id;

  // Initialize debug mode from localStorage on component mount
  useEffect(() => {
    initializeDebugMode();
    setDebugEnabled(isDebugEnabled());
  }, []);

  //////////////////////////////////////////////////////////////////////////////
  // FHEVM instance
  //////////////////////////////////////////////////////////////////////////////

  // Create EIP-1193 provider from wagmi for FHEVM
  const provider = useMemo(() => {
    if (typeof window === "undefined") return undefined;

    // Get the wallet provider from window.ethereum
    return (window as any).ethereum;
  }, []);

  const initialMockChains = { 31337: "http://localhost:8545" };

  const {
    instance: fhevmInstance,
    status: fhevmStatus,
    error: fhevmError,
  } = useFhevm({
    provider,
    chainId,
    initialMockChains,
    enabled: true, // use enabled to dynamically create the instance on-demand
  });

  //////////////////////////////////////////////////////////////////////////////
  // IndexedDB Storage for persistent decryption signatures
  // This means signatures survive page reload - user doesn't need to re-sign!
  //////////////////////////////////////////////////////////////////////////////

  const { storage: indexedDBStorage, isReady: storageReady, error: storageError } = useIndexedDBStorage({
    dbName: "fhevm-nextjs-app",
    storeName: "signatures",
  });

  //////////////////////////////////////////////////////////////////////////////
  // useFHECounter is a custom hook containing all the FHECounter logic, including
  // - calling the FHECounter contract
  // - encrypting FHE inputs
  // - decrypting FHE handles (with persistent storage!)
  //////////////////////////////////////////////////////////////////////////////

  const fheCounter = useFHECounterWagmi({
    instance: fhevmInstance,
    initialMockChains,
    storage: indexedDBStorage, // Use IndexedDB for persistence
  });

  //////////////////////////////////////////////////////////////////////////////
  // UI Stuff:
  // --------
  // A basic page containing
  // - A bunch of debug values allowing you to better visualize the React state
  // - 1x "Decrypt" button (to decrypt the latest FHECounter count handle)
  // - 1x "Increment" button (to increment the FHECounter)
  // - 1x "Decrement" button (to decrement the FHECounter)
  //////////////////////////////////////////////////////////////////////////////

  // DaisyUI cyberpunk theme button classes
  const primaryButtonClass = "btn btn-primary btn-lg";
  const secondaryButtonClass = "btn btn-secondary btn-lg";
  const successButtonClass = "btn btn-accent btn-lg";

  const titleClass = "font-bold text-xl mb-4 border-b border-base-content/20 pb-2";
  const sectionClass = "bg-base-200 shadow-xl p-6 mb-6";

  if (!isConnected) {
    return (
      <div className="max-w-6xl mx-auto p-6">
        <div className="flex items-center justify-center">
          <div className="card bg-base-100 shadow-xl p-8 text-center max-w-md">
            <div className="mb-4">
              <span className="inline-flex items-center justify-center w-14 h-14 rounded-full bg-warning/30 text-warning text-3xl">
                ⚠️
              </span>
            </div>
            <h2 className="text-2xl font-extrabold mb-2">Wallet not connected</h2>
            <p className="text-base-content/70 mb-6">Connect your wallet to use the FHE Counter demo.</p>
            <div className="flex items-center justify-center">
              <RainbowKitCustomConnectButton />
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto p-6 space-y-6">
      {/* Header */}
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold mb-2">🔐 FHE Counter Demo</h1>
        <p className="text-base-content/70">Interact with the Fully Homomorphic Encryption Counter contract</p>
        <div className="mt-4 flex justify-center gap-2 flex-wrap">
          <button
            onClick={() => {
              const newState = toggleDebugMode();
              setDebugEnabled(newState);
              logDebug(`Debug mode ${newState ? "enabled" : "disabled"}`);
            }}
            className={`btn btn-sm gap-2 ${debugEnabled ? "btn-info" : "btn-ghost"}`}
          >
            🐛 {debugEnabled ? "Debug ON" : "Debug OFF"}
          </button>
        </div>
      </div>

      {/* Count Handle Display */}
      <div className={sectionClass}>
        <h3 className={titleClass}>🔢 Count Handle</h3>
        <div className="space-y-3 space-x-3">
          {printProperty("Encrypted Handle", fheCounter.handle || "No handle available")}
          {printProperty("Decrypted Value", fheCounter.isDecrypted ? fheCounter.clear : "Not decrypted yet")}
        </div>
      </div>

      {/* Action Buttons */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <button
          className={fheCounter.isDecrypted ? successButtonClass : primaryButtonClass}
          disabled={!fheCounter.canDecrypt}
          onClick={fheCounter.decryptCountHandle}
        >
          {fheCounter.canDecrypt
            ? "🔓 Decrypt Counter"
            : fheCounter.isDecrypted
              ? `✅ Decrypted: ${fheCounter.clear}`
              : fheCounter.isDecrypting
                ? "⏳ Decrypting..."
                : "❌ Nothing to decrypt"}
        </button>

        <button
          className={secondaryButtonClass}
          disabled={!fheCounter.canUpdateCounter}
          onClick={() => fheCounter.updateCounter(+1)}
        >
          {fheCounter.canUpdateCounter
            ? "➕ Increment +1"
            : fheCounter.isProcessing
              ? "⏳ Processing..."
              : "❌ Cannot increment"}
        </button>

        <button
          className={secondaryButtonClass}
          disabled={!fheCounter.canUpdateCounter}
          onClick={() => fheCounter.updateCounter(-1)}
        >
          {fheCounter.canUpdateCounter
            ? "➖ Decrement -1"
            : fheCounter.isProcessing
              ? "⏳ Processing..."
              : "❌ Cannot decrement"}
        </button>
      </div>

      {/* Messages */}
      {fheCounter.message && (
        <div className={sectionClass}>
          <h3 className={titleClass}>💬 Messages</h3>
          <div className="alert alert-info">
            <p>{fheCounter.message}</p>
          </div>
        </div>
      )}

      {/* Status Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className={sectionClass}>
          <h3 className={titleClass}>🔧 FHEVM Instance</h3>
          <div className="space-y-3">
            {printProperty("Instance Status", fhevmInstance ? "✅ Connected" : "❌ Disconnected")}
            {printProperty("Status", fhevmStatus)}
            {printProperty("Error", fhevmError ?? "No errors")}
          </div>
        </div>

        <div className={sectionClass}>
          <h3 className={titleClass}>💾 Storage</h3>
          <div className="space-y-3">
            {printProperty("Type", storageReady ? "IndexedDB" : "Initializing...")}
            {printProperty("Status", storageReady ? "✅ Ready" : "⏳ Loading")}
            {printProperty("Persistent", storageReady && !storageError ? "✅ Yes" : "❌ No")}
            {storageError && printProperty("Fallback", "localStorage/memory")}
          </div>
        </div>

        <div className={sectionClass}>
          <h3 className={titleClass}>📊 Counter Status</h3>
          <div className="space-y-3">
            {printProperty("Refreshing", fheCounter.isRefreshing)}
            {printProperty("Decrypting", fheCounter.isDecrypting)}
            {printProperty("Processing", fheCounter.isProcessing)}
            {printProperty("Can Get Count", fheCounter.canGetCount)}
            {printProperty("Can Decrypt", fheCounter.canDecrypt)}
            {printProperty("Can Modify", fheCounter.canUpdateCounter)}
          </div>
        </div>
      </div>
    </div>
  );
};

function printProperty(name: string, value: unknown) {
  let displayValue: string;

  if (typeof value === "boolean") {
    return printBooleanProperty(name, value);
  } else if (typeof value === "string" || typeof value === "number") {
    displayValue = String(value);
  } else if (typeof value === "bigint") {
    displayValue = String(value);
  } else if (value === null) {
    displayValue = "null";
  } else if (value === undefined) {
    displayValue = "undefined";
  } else if (value instanceof Error) {
    displayValue = value.message;
  } else {
    displayValue = JSON.stringify(value);
  }
  return (
    <div className="flex justify-between items-center py-2 px-3 bg-base-100 border border-base-content/20 w-full rounded">
      <span className="font-medium">{name}</span>
      <span className="ml-2 font-mono text-sm font-semibold bg-base-300 px-2 py-1 rounded">
        {displayValue}
      </span>
    </div>
  );
}

function printBooleanProperty(name: string, value: boolean) {
  return (
    <div className="flex justify-between items-center py-2 px-3 bg-base-100 border border-base-content/20 w-full rounded">
      <span className="font-medium">{name}</span>
      <span className={`badge badge-lg ${value ? "badge-success" : "badge-error"}`}>
        {value ? "✓ true" : "✗ false"}
      </span>
    </div>
  );
}
